const $=id=>document.getElementById(id);
const state={project:null,images:[],groups:[],current:null,image:null,tool:'roi',draft:[],roi:[],leftEdges:new Set(),rightEdges:new Set(),exclusions:[],grayCard:[],contours:null,metrics:null,parameterHash:null,classificationOverlays:{},overlayImages:{},scale:1,offsetX:0,offsetY:0,drag:null,painting:false,dirty:false,selectedImages:new Set(),analysisTimer:null,analysisSerial:0,autoDatabasePath:''};

async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||`请求失败 (${response.status})`);return data}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),2800)}
function escapeHtml(text){return String(text??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function post(path,data){return api(path,{method:'POST',body:JSON.stringify(data)})}

async function browse(kind,input){try{const route=kind==='folder'?'/api/dialog/folder':kind==='save'?'/api/dialog/save-project':'/api/dialog/open-project';const result=await post(route,{initial:input.value});if(result.path)input.value=result.path;return result.path||''}catch(e){toast(e.message);return''}}
$('browseSource').onclick=async()=>{if(await browse('folder',$('sourcePath')))refreshDefaultProjectPath()};
$('browseSave').onclick=()=>browse('save',$('databasePath'));
$('browseOpen').onclick=()=>browse('open',$('openPath'));
$('browseExport').onclick=()=>browse('folder',$('exportPath'));
function refreshDefaultProjectPath(){const source=$('sourcePath').value.trim().replace(/[\\/]+$/,'');const name=$('newName').value.trim().replace(/[<>:"/\\|?*\x00-\x1f]+/g,'_').replace(/[ .]+$/,'')||'coat_analysis_project';const previous=state.autoDatabasePath;state.autoDatabasePath=source?`${source}${source.includes('\\')?'\\':'/'}${name}.sqlite`:'';if(!$('databasePath').value||$('databasePath').value===previous)$('databasePath').value=state.autoDatabasePath}
$('sourcePath').oninput=refreshDefaultProjectPath;$('newName').oninput=refreshDefaultProjectPath;
$('createProject').onclick=async()=>{try{if(!$('newName').value.trim())throw new Error('请填写项目名称');$('createProject').disabled=true;$('createProject').textContent='正在扫描图片…';state.project=await post('/api/project/create',{name:$('newName').value,source_root:$('sourcePath').value,database_path:$('databasePath').value});await enterProject()}catch(e){toast(e.message)}finally{$('createProject').disabled=false;$('createProject').textContent='扫描照片并创建'}};
$('openProject').onclick=async()=>{try{state.project=await post('/api/project/open',{database_path:$('openPath').value});await enterProject()}catch(e){toast(e.message)}};

async function enterProject(){[$('homeView'),$('groupsView'),$('exportView')].forEach(el=>el.classList.add('hidden'));$('annotateView').classList.remove('hidden');$('mainNav').classList.remove('hidden');$('projectBadge').textContent=`${state.project.name} · ${state.project.image_count} 张`;syncSettings();await reloadData();if(state.images.length)await selectImage(state.images[0].id)}
async function reloadData(){[state.images,state.groups]=await Promise.all([api('/api/images'),api('/api/groups')]);renderImageList();renderGroups();$('progressText').textContent=`${state.images.filter(x=>x.status==='reviewed').length}/${state.images.length} 已确认`}
document.querySelectorAll('#mainNav button').forEach(button=>button.onclick=async()=>{document.querySelectorAll('#mainNav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.app-view').forEach(x=>x.classList.add('hidden'));$(`${button.dataset.view}View`).classList.remove('hidden');if(button.dataset.view==='groups'){await reloadData()}if(button.dataset.view==='export'){state.project=await api('/api/project');syncSettings()}});

function renderImageList(){const filter=$('imageFilter').value.trim().toLowerCase();$('imageList').innerHTML=state.images.filter(x=>x.relative_path.toLowerCase().includes(filter)).map(x=>`<div class="image-item ${escapeHtml(x.status)} ${state.current?.id===x.id?'active':''}" data-id="${x.id}" title="${escapeHtml(x.relative_path)}">${escapeHtml(x.relative_path)}</div>`).join('');document.querySelectorAll('.image-item').forEach(el=>el.onclick=()=>selectImage(+el.dataset.id))}
$('imageFilter').oninput=renderImageList;

async function selectImage(id){try{if(state.current&&state.current.id!==id&&state.dirty)await saveCurrent('not_reviewed',false);state.current=await api(`/api/image-meta?id=${id}`);state.roi=state.current.roi||[];state.leftEdges=new Set(state.current.left_edges||[]);state.rightEdges=new Set(state.current.right_edges||[]);state.exclusions=state.current.exclusions||[];state.grayCard=state.current.gray_card||[];state.draft=[];state.contours=null;state.metrics=null;state.parameterHash=null;state.classificationOverlays={};state.overlayImages={};state.dirty=false;$('splitLeft').value=Math.round(state.current.split_left*100);$('splitRight').value=Math.round(state.current.split_right*100);$('whiteDepthMin').value=state.current.white_depth_min??0;$('whiteDepthMax').value=state.current.white_depth_max??25;$('blackDepthMin').value=state.current.black_depth_min??60;$('blackDepthMax').value=state.current.black_depth_max??100;syncSplitLabels();validateHairRanges(false);$('currentName').textContent=state.current.filename;$('currentMeta').textContent=`${state.current.width} × ${state.current.height} · ${state.current.group_name||'未分组'} · ${statusText(state.current.status)}`;$('analysisStatus').textContent='标注已载入，尚未重新计算';renderMetrics();renderImageList();const image=new Image();image.onload=()=>{state.image=image;const canvas=$('mainCanvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;$('canvasHint').classList.add('hidden');fitImage();draw();if(canAnalyze())scheduleAnalyze(50)};image.onerror=()=>toast('原始图片读取失败');image.src=`/api/image-data?id=${id}&t=${Date.now()}`}catch(e){toast(e.message)}}
function statusText(status){return({not_reviewed:'未确认',reviewed:'已确认',low_quality:'低质量',no_visible_region:'无可识别区域'})[status]||status}

const wrap=$('canvasWrap'),canvas=$('mainCanvas'),ctx=canvas.getContext('2d');
function fitImage(){if(!state.image)return;state.scale=Math.min((wrap.clientWidth-30)/state.image.width,(wrap.clientHeight-30)/state.image.height,1);state.offsetX=(wrap.clientWidth-state.image.width*state.scale)/2;state.offsetY=(wrap.clientHeight-state.image.height*state.scale)/2;applyTransform()}
function applyTransform(){canvas.style.transform=`translate(${state.offsetX}px,${state.offsetY}px) scale(${state.scale})`;$('zoomText').textContent=`${Math.round(state.scale*100)}%`}
function imagePoint(event){const rect=wrap.getBoundingClientRect();return[(event.clientX-rect.left-state.offsetX)/state.scale,(event.clientY-rect.top-state.offsetY)/state.scale]}
function insideImage(p){return state.image&&p[0]>=0&&p[1]>=0&&p[0]<state.image.width&&p[1]<state.image.height}
function draw(){if(!state.image)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(state.image,0,0);drawHairOverlay();if(state.roi.length>=3){ctx.save();ctx.fillStyle='rgba(255,215,0,.07)';ctx.beginPath();pathPolygon(state.roi,true);ctx.fill();ctx.restore();drawPolygon(state.roi,'#ffd700',3,true);drawEdges()}state.exclusions.forEach(p=>{fillPolygon(p,'rgba(255,0,255,.16)');drawPolygon(p,'#ff00ff',3,true)});if(state.grayCard.length){fillPolygon(state.grayCard,'rgba(0,214,189,.16)');drawPolygon(state.grayCard,'#00d6bd',3,true)}if(state.draft.length)drawPolygon(state.draft,toolColor(state.tool),3,false);if(state.contours){drawSegments(state.contours.left_middle,'#00e676',4);drawSegments(state.contours.middle_right,'#ff8c00',4)}}
function drawHairOverlay(){if(!$('showHairOverlay').checked)return;const mode=$('metricMode').value;const image=state.overlayImages[mode];if(image?.complete)ctx.drawImage(image,0,0,canvas.width,canvas.height)}
function clearComputed(){state.contours=null;state.metrics=null;state.parameterHash=null;state.classificationOverlays={};state.overlayImages={}}
function pathPolygon(points,closed){ctx.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length;i++)ctx.lineTo(points[i][0],points[i][1]);if(closed)ctx.closePath()}
function drawPolygon(points,color,width,closed){if(!points.length)return;ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=width/state.scale;ctx.beginPath();pathPolygon(points,closed);ctx.stroke();for(const p of points){ctx.beginPath();ctx.arc(p[0],p[1],4/state.scale,0,Math.PI*2);ctx.fill()}ctx.restore()}
function fillPolygon(points,color){if(points.length<3)return;ctx.save();ctx.fillStyle=color;ctx.beginPath();pathPolygon(points,true);ctx.fill();ctx.restore()}
function drawEdges(){const n=state.roi.length;for(const i of state.leftEdges)drawEdge(i,'#1e90ff');for(const i of state.rightEdges)drawEdge(i,'#ff5050');function drawEdge(i,color){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=8/state.scale;ctx.beginPath();ctx.moveTo(...state.roi[i%n]);ctx.lineTo(...state.roi[(i+1)%n]);ctx.stroke();ctx.restore()}}
function drawSegments(segments,color,width){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width/state.scale;ctx.beginPath();for(const [a,b] of segments){ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1])}ctx.stroke();ctx.restore()}
function toolColor(tool){return tool==='exclude'?'#ff00ff':tool==='gray'?'#00d6bd':'#ffd700'}

wrap.onpointerdown=e=>{if(!state.image)return;const p=imagePoint(e);if(state.tool==='pan'){state.drag={x:e.clientX,y:e.clientY,ox:state.offsetX,oy:state.offsetY};wrap.setPointerCapture(e.pointerId);return}if(!insideImage(p))return;if(state.tool==='left'||state.tool==='right'){state.painting=true;paintEdge(p,true);wrap.setPointerCapture(e.pointerId);return}if(['roi','exclude','gray'].includes(state.tool)){if(state.tool==='roi'&&state.roi.length){state.roi=[];state.leftEdges.clear();state.rightEdges.clear();clearComputed()}state.draft.push(p);state.dirty=true;draw()}};
wrap.onpointermove=e=>{if(state.drag){state.offsetX=state.drag.ox+e.clientX-state.drag.x;state.offsetY=state.drag.oy+e.clientY-state.drag.y;applyTransform()}else if(state.painting)paintEdge(imagePoint(e),false)};
wrap.onpointerup=e=>{state.drag=null;state.painting=false;try{wrap.releasePointerCapture(e.pointerId)}catch{}};
wrap.onwheel=e=>{if(!state.image)return;e.preventDefault();const rect=wrap.getBoundingClientRect(),mx=e.clientX-rect.left,my=e.clientY-rect.top,ix=(mx-state.offsetX)/state.scale,iy=(my-state.offsetY)/state.scale,next=Math.max(.08,Math.min(10,state.scale*(e.deltaY<0?1.15:.87)));state.offsetX=mx-ix*next;state.offsetY=my-iy*next;state.scale=next;applyTransform()};
wrap.oncontextmenu=e=>e.preventDefault();
function nearestEdge(p){if(state.roi.length<3)return[-1,Infinity];let best=-1,distance=Infinity;for(let i=0;i<state.roi.length;i++){const d=segmentDistance(p,state.roi[i],state.roi[(i+1)%state.roi.length]);if(d<distance){distance=d;best=i}}return[best,distance]}
function segmentDistance(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],den=dx*dx+dy*dy;const t=den?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/den)):0;return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy)}
function paintEdge(p,toggle){const[index,distance]=nearestEdge(p);if(index<0||distance>18/state.scale)return;const own=state.tool==='left'?state.leftEdges:state.rightEdges,other=state.tool==='left'?state.rightEdges:state.leftEdges;if(toggle&&own.has(index))own.delete(index);else{own.add(index);other.delete(index)}state.dirty=true;clearComputed();draw()}

$('finishPolygon').onclick=()=>{if(state.draft.length<3){toast('当前图形至少需要 3 个点');return}if(state.tool==='roi'){state.roi=state.draft;state.leftEdges.clear();state.rightEdges.clear()}else if(state.tool==='exclude')state.exclusions.push(state.draft);else if(state.tool==='gray')state.grayCard=state.draft;else{toast('当前工具不需要闭合图形');return}state.draft=[];state.dirty=true;clearComputed();draw();scheduleAnalyze(100)};
$('undo').onclick=()=>{if(state.draft.length)state.draft.pop();else if(state.tool==='exclude'&&state.exclusions.length)state.exclusions.pop();else if(state.tool==='gray')state.grayCard=[];else if(state.tool==='roi'&&state.roi.length){state.roi.pop();state.leftEdges.clear();state.rightEdges.clear()}state.dirty=true;clearComputed();draw()};
$('fitImage').onclick=fitImage;
const help={pan:'拖动画面；滚轮缩放。',roi:'单击添加手术区顶点，完成后点击“闭合当前图形”。重新绘制会替换原手术区。',left:'在 ROI 边界上单击或拖动，涂选连续的左边缘线段。',right:'在 ROI 边界上单击或拖动，涂选连续的右边缘线段。',exclude:'单击添加不参与颜色统计的区域，可绘制多个。',gray:'圈选灰卡区域；再次绘制会替换原灰卡。'};
document.querySelectorAll('#toolButtons button').forEach(button=>button.onclick=()=>{state.tool=button.dataset.tool;state.draft=[];document.querySelectorAll('#toolButtons button').forEach(x=>x.classList.toggle('active',x===button));$('toolHelp').textContent=help[state.tool];wrap.style.cursor=state.tool==='pan'?'grab':'crosshair';draw()});

function syncSplitLabels(){let left=+$('splitLeft').value,right=+$('splitRight').value;if(left>=right){if(document.activeElement===$('splitLeft'))left=right-1;else right=left+1;$('splitLeft').value=left;$('splitRight').value=right}$('splitLeftLabel').textContent=`${left}%`;$('splitRightLabel').textContent=`${right}%`;state.dirty=true}
[$('splitLeft'),$('splitRight')].forEach(input=>input.oninput=()=>{syncSplitLabels();scheduleAnalyze(180)});
function payload(){return{image_id:state.current.id,roi:state.roi,left_edges:[...state.leftEdges].sort((a,b)=>a-b),right_edges:[...state.rightEdges].sort((a,b)=>a-b),exclusions:state.exclusions,gray_card:state.grayCard,split_left:+$('splitLeft').value/100,split_right:+$('splitRight').value/100,white_depth_min:+$('whiteDepthMin').value,white_depth_max:+$('whiteDepthMax').value,black_depth_min:+$('blackDepthMin').value,black_depth_max:+$('blackDepthMax').value}}
function canAnalyze(){return state.current&&state.roi.length>=3&&state.leftEdges.size&&state.rightEdges.size}
function scheduleAnalyze(delay=200){clearTimeout(state.analysisTimer);if(canAnalyze()&&validateHairRanges(false))state.analysisTimer=setTimeout(analyzeCurrent,delay)}
async function analyzeCurrent(){if(!canAnalyze()){toast('请先完成手术区，并标记连续的左、右边缘');return}if(!validateHairRanges(true))return;const serial=++state.analysisSerial;$('analysisStatus').textContent='正在计算调和分区与黑白发面积…';try{const result=await post('/api/analyze',payload());if(serial!==state.analysisSerial)return;state.contours=result.contours;state.metrics=result.metrics;state.parameterHash=result.parameter_hash;loadClassificationOverlays(result.classification_overlays||{});$('analysisStatus').textContent=`计算完成 · ${result.solver.iterations} 次迭代`;draw();renderMetrics()}catch(e){if(serial===state.analysisSerial){state.contours=null;state.metrics=null;state.classificationOverlays={};state.overlayImages={};$('analysisStatus').textContent=e.message;draw();renderMetrics()}}}
$('calculate').onclick=analyzeCurrent;
function renderMetrics(){if(!state.metrics){$('metricModeNote').textContent='';$('metricCards').innerHTML='<div class="empty">完成 ROI 和左右边缘后显示</div>';renderHairAreas();return}const gray=!!state.metrics.gray_card.available;const correctedOption=$('metricMode').querySelector('option[value="gray_corrected"]');correctedOption.disabled=!gray;if(!gray&&$('metricMode').value==='gray_corrected')$('metricMode').value='raw';const corrected=$('metricMode').value==='gray_corrected';$('metricModeNote').textContent=gray?`灰卡观测 L* ${Number(state.metrics.gray_card.observed_l).toFixed(1)}，目标 L* ${Number(state.metrics.gray_card.target_l).toFixed(1)}`:'当前图片未标注灰卡，只能显示原始结果。';const rows=[['left','左侧'],['middle','中间'],['right','右侧']];$('metricCards').innerHTML=rows.map(([key,label])=>{const m=state.metrics.regions[key];const value=corrected?m.mean_corrected_darkness:m.mean_darkness;return`<div class="metric-card ${key}"><small>${label}</small><strong>${Number(value).toFixed(1)}</strong><small>${corrected?'灰卡校正颜色深度':'原始颜色深度'}<br>${m.pixel_count.toLocaleString()} px</small></div>`}).join('');renderHairAreas()}
$('metricMode').onchange=()=>{renderMetrics();draw()};
$('showHairOverlay').onchange=draw;

function validateHairRanges(notify){const w0=+$('whiteDepthMin').value,w1=+$('whiteDepthMax').value,b0=+$('blackDepthMin').value,b1=+$('blackDepthMax').value;let message='';if([w0,w1,b0,b1].some(x=>!Number.isFinite(x)||x<0||x>100))message='四个范围值都必须在 0–100 之间';else if(w0>=w1||b0>=b1)message='每个范围的下限必须小于上限';else if(w1>b0)message='白发与黑发范围不能重叠';$('hairRangeNote').textContent=message||`未分类范围：${w1}–${b0}（另外，低于 ${w0} 或高于 ${b1} 的像素也不分类）`;if(message&&notify)toast(message);return!message}
[$('whiteDepthMin'),$('whiteDepthMax'),$('blackDepthMin'),$('blackDepthMax')].forEach(input=>input.oninput=()=>{state.dirty=true;state.metrics=null;state.parameterHash=null;state.classificationOverlays={};state.overlayImages={};validateHairRanges(false);draw();renderMetrics();scheduleAnalyze(250)});

function loadClassificationOverlays(overlays){state.classificationOverlays=overlays;state.overlayImages={};for(const[mode,source]of Object.entries(overlays)){const image=new Image();image.onload=draw;image.src=source;state.overlayImages[mode]=image}}
function renderHairAreas(){if(!state.metrics?.hair_classification){$('hairAreaCards').innerHTML='<div class="empty">完成分析后显示</div>';$('hairRegionTable').innerHTML='';return}const mode=$('metricMode').value;const data=state.metrics.hair_classification.modes[mode];if(!data){$('hairAreaCards').innerHTML='<div class="empty">当前模式无可用结果</div>';return}const a=data.overall;$('hairAreaCards').innerHTML=`<div class="hair-area-card white"><small>白发面积</small><strong>${(a.white_area_fraction*100).toFixed(2)}%</strong><small>${a.white_pixel_count.toLocaleString()} px</small></div><div class="hair-area-card black"><small>黑发面积</small><strong>${(a.black_area_fraction*100).toFixed(2)}%</strong><small>${a.black_pixel_count.toLocaleString()} px</small></div>`;const labels={left:'左侧',middle:'中间',right:'右侧'};$('hairRegionTable').innerHTML=`<table class="hair-region-table"><thead><tr><th>亚区</th><th>白发</th><th>黑发</th><th>未分类</th></tr></thead><tbody>${Object.entries(data.regions).map(([key,m])=>`<tr><td>${labels[key]}</td><td>${(m.white_area_fraction*100).toFixed(1)}%</td><td>${(m.black_area_fraction*100).toFixed(1)}%</td><td>${(m.unclassified_area_fraction*100).toFixed(1)}%</td></tr>`).join('')}</tbody></table>`}
async function saveCurrent(status='not_reviewed',notify=true){if(!state.current)return;const data={...payload(),status,metrics:state.metrics,parameter_hash:state.parameterHash};await post('/api/annotation/save',data);state.dirty=false;await reloadData();state.current.status=status;if(notify)toast(status==='reviewed'?'当前图片已确认':status==='low_quality'?'已标记低质量':status==='no_visible_region'?'已标记无可识别手术区':'草稿已保存')}
$('saveDraft').onclick=()=>saveCurrent('not_reviewed');
$('confirmNext').onclick=async()=>{try{if(!state.metrics)await analyzeCurrent();if(!state.metrics)throw new Error('分区尚未成功计算');const index=state.images.findIndex(x=>x.id===state.current.id);await saveCurrent('reviewed');const next=state.images.slice(index+1).find(x=>x.status!=='reviewed');if(next)await selectImage(next.id)}catch(e){toast(e.message)}};
$('markLow').onclick=()=>saveCurrent('low_quality');
$('markNoRegion').onclick=async()=>{try{const empty={...payload(),roi:[],left_edges:[],right_edges:[],exclusions:[],gray_card:[],status:'no_visible_region'};await post('/api/annotation/save',empty);state.dirty=false;await reloadData();toast('已标记无可识别手术区')}catch(e){toast(e.message)}};

function renderGroups(){if(!state.groups)return;$('groupList').innerHTML=state.groups.length?state.groups.map(g=>`<div class="group-entry"><strong>${escapeHtml(g.name)}</strong><span>${g.image_count} 张</span></div>`).join(''):'<p class="muted">尚无实验组</p>';$('assignGroupSelect').innerHTML='<option value="">移至未分组</option>'+state.groups.map(g=>`<option value="${g.id}">${escapeHtml(g.name)}</option>`).join('');renderGroupTable()}
function renderGroupTable(){const filter=$('groupFilter').value.trim().toLowerCase();const visible=state.images.filter(x=>x.relative_path.toLowerCase().includes(filter));$('groupImageTable').innerHTML=visible.map(x=>`<tr><td><input type="checkbox" data-image-check="${x.id}" ${state.selectedImages.has(x.id)?'checked':''}></td><td>${escapeHtml(x.relative_path)}</td><td>${escapeHtml(x.group_name||'未分组')}</td><td>${statusText(x.status)}</td></tr>`).join('');document.querySelectorAll('[data-image-check]').forEach(x=>x.onchange=()=>x.checked?state.selectedImages.add(+x.dataset.imageCheck):state.selectedImages.delete(+x.dataset.imageCheck))}
$('groupFilter').oninput=renderGroupTable;
$('addGroup').onclick=async()=>{try{await post('/api/groups/create',{name:$('groupName').value});$('groupName').value='';await reloadData();toast('实验组已添加')}catch(e){toast(e.message)}};
$('selectVisible').onclick=()=>{const filter=$('groupFilter').value.trim().toLowerCase();state.images.filter(x=>x.relative_path.toLowerCase().includes(filter)).forEach(x=>state.selectedImages.add(x.id));renderGroupTable()};
$('clearSelection').onclick=()=>{state.selectedImages.clear();renderGroupTable()};
$('assignSelected').onclick=async()=>{try{if(!state.selectedImages.size)throw new Error('请先勾选图片');const value=$('assignGroupSelect').value;await post('/api/groups/assign',{group_id:value?+value:null,image_ids:[...state.selectedImages]});state.selectedImages.clear();await reloadData();toast('批量分组已保存')}catch(e){toast(e.message)}};

function syncSettings(){if(!state.project)return;$('useStandard').checked=!!state.project.use_standard_export;$('standardLeft').value=Math.round(state.project.standard_left*100);$('standardRight').value=Math.round(state.project.standard_right*100);$('grayTarget').value=state.project.gray_target_l;if(!$('exportPath').value)$('exportPath').value=state.project.source_root||''}
$('saveSettings').onclick=async()=>{try{state.project=await post('/api/settings',{use_standard_export:$('useStandard').checked,standard_left:+$('standardLeft').value/100,standard_right:+$('standardRight').value/100,gray_target_l:+$('grayTarget').value});syncSettings();toast('项目设置已保存')}catch(e){toast(e.message)}};
$('exportResults').onclick=async()=>{try{$('exportResults').disabled=true;$('exportStatus').textContent='正在重新计算已确认图片并导出…';const result=await post('/api/export',{output_root:$('exportPath').value});$('exportStatus').textContent=`导出完成：${result.output_path}`;toast('导出完成')}catch(e){$('exportStatus').textContent=e.message;toast(e.message)}finally{$('exportResults').disabled=false}};

window.addEventListener('resize',()=>{if(state.image)fitImage()});
(async()=>{try{state.project=await api('/api/project');if(state.project)await enterProject()}catch(e){toast(e.message)}})();
